name: Publish modelbox images
on:
  workflow_dispatch:

jobs:
  test_armd_ubuntu:
    runs-on: ubuntu
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: CMake
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DWITH_ALL_DEMO=on -DWITH_WEBUI=on -DUSE_CN_MIRROR=yes
    - name: Build
      working-directory: build
      run: |
        make package -j4
    - name: Release check
      run: ./docker/artifact_check.sh
      shell: bash
    - name: Test
      working-directory: build
      run: | 
        make build-test -j4
        make unittest

  test_armd_openeuler:
    runs-on: openeuler
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: CMake
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DWITH_ALL_DEMO=on -DWITH_WEBUI=on -DUSE_CN_MIRROR=yes
    - name: Build
      working-directory: build
      run: |
        make package -j4
    - name: Release check
      run: ./docker/artifact_check.sh
      shell: bash
    - name: Test
      working-directory: build
      run: | 
        make build-test -j4
        make unittest
